use handlebars::Handlebars;
use serde::Serialize;
use serde_json::json;

pub fn create_brew<T: Serialize>(data: &T) -> String {
    let reg = Handlebars::new();
    reg.render_template(TEMPLATE, data).unwrap()
}

const TEMPLATE: &str = r###"# typed: false
# frozen_string_literal: true
# This file was generated by releaser. DO NOT EDIT.
class {{ name }} < Formula
  desc "{{ desc }}"
  homepage "{{ homepage }}"
  version "{{ version }}"
  {{#if license }}
  license "{{ license }}"
  {{/if}}
  {{#if macOS }}
  on_macos do
    if Hardware::CPU.intel?
    {{#with macOS}}
      url "{{ url }}"
      sha256 "{{ hash }}"
     {{/with}}
    end
  end
  {{/if}}
  {{#if linux }}
  on_linux do
    if Hardware::CPU.intel?
    {{#with linux}}
      url "{{ url }}"
      sha256 "{{ hash }}"
    {{/with}}
    end
  end
  {{/if}}
end
"###;

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn create_brew_no_packages_test() {
        // Arrange

        // Act
        let result = create_brew(
            &json!({"name": "Solv", "desc" : "desc", "version": "v0.4.0", "license" : "MIT"}),
        );

        // Assert
        assert_eq!(
            r###"# typed: false
# frozen_string_literal: true
# This file was generated by releaser. DO NOT EDIT.
class Solv < Formula
  desc "desc"
  homepage ""
  version "v0.4.0"
  license "MIT"
end
"###,
            result
        )
    }

    #[test]
    fn create_brew_macos_test() {
        // Arrange

        // Act
        let result = create_brew(
            &json!({"name": "Solv", "desc" : "desc", "version": "v0.4.0", "license" : "MIT", "macOS" : {
                "url" : "https://github.com/aegoroff/solt/releases/download/v1.0.7/solt_1.0.7_darwin_amd64.tar.gz",
                "hash" : "9a6c8144ed77cd5e2b88031109ac4285ca08e8c644f3d022a389359470721a7b"
            }}),
        );

        // Assert
        assert_eq!(
            r###"# typed: false
# frozen_string_literal: true
# This file was generated by releaser. DO NOT EDIT.
class Solv < Formula
  desc "desc"
  homepage ""
  version "v0.4.0"
  license "MIT"
  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/aegoroff/solt/releases/download/v1.0.7/solt_1.0.7_darwin_amd64.tar.gz"
      sha256 "9a6c8144ed77cd5e2b88031109ac4285ca08e8c644f3d022a389359470721a7b"
    end
  end
end
"###,
            result
        )
    }

    #[test]
    fn create_brew_linux_test() {
        // Arrange

        // Act
        let result = create_brew(
            &json!({"name": "Solv", "desc" : "desc", "version": "v0.4.0", "license" : "MIT", "linux" : {
                "url" : "https://github.com/aegoroff/solt/releases/download/v1.0.7/solt_1.0.7_linux_amd64.tar.gz",
                "hash" : "fb5c2f5d41c7d3485898de9905736dc8c540a912dc95d3a55bd9360901689811"
            }}),
        );

        // Assert
        assert_eq!(
            r###"# typed: false
# frozen_string_literal: true
# This file was generated by releaser. DO NOT EDIT.
class Solv < Formula
  desc "desc"
  homepage ""
  version "v0.4.0"
  license "MIT"
  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/aegoroff/solt/releases/download/v1.0.7/solt_1.0.7_linux_amd64.tar.gz"
      sha256 "fb5c2f5d41c7d3485898de9905736dc8c540a912dc95d3a55bd9360901689811"
    end
  end
end
"###,
            result
        )
    }

    #[test]
    fn create_brew_all_test() {
        // Arrange

        // Act
        let result = create_brew(
            &json!({"name": "Solv", "desc" : "desc", "version": "v0.4.0", "license" : "MIT", "macOS" : {
                "url" : "https://github.com/aegoroff/solt/releases/download/v1.0.7/solt_1.0.7_darwin_amd64.tar.gz",
                "hash" : "9a6c8144ed77cd5e2b88031109ac4285ca08e8c644f3d022a389359470721a7b"
            },
            "linux" : {
                "url" : "https://github.com/aegoroff/solt/releases/download/v1.0.7/solt_1.0.7_linux_amd64.tar.gz",
                "hash" : "fb5c2f5d41c7d3485898de9905736dc8c540a912dc95d3a55bd9360901689811"
            }}),
        );

        // Assert
        assert_eq!(
            r###"# typed: false
# frozen_string_literal: true
# This file was generated by releaser. DO NOT EDIT.
class Solv < Formula
  desc "desc"
  homepage ""
  version "v0.4.0"
  license "MIT"
  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/aegoroff/solt/releases/download/v1.0.7/solt_1.0.7_darwin_amd64.tar.gz"
      sha256 "9a6c8144ed77cd5e2b88031109ac4285ca08e8c644f3d022a389359470721a7b"
    end
  end
  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/aegoroff/solt/releases/download/v1.0.7/solt_1.0.7_linux_amd64.tar.gz"
      sha256 "fb5c2f5d41c7d3485898de9905736dc8c540a912dc95d3a55bd9360901689811"
    end
  end
end
"###,
            result
        )
    }
}
